// Generated by CoffeeScript 1.6.2
(function() {
  var aio, app, connect, port;

  port = process.env.APP_PORT || 8080;

  connect = require('connect');

  aio = require('./spts/lib/allInOne')();

  app = connect();

  app.use(connect["static"]("" + __dirname + "/public"));

  app.use('/s/', aio.middleWare);

  app.listen(port);

}).call(this);
