// Generated by CoffeeScript 1.6.2
var aio, allinone, app, connect, e, port;

try {
  //require('coffee-script');
  connect = require('connect');
  allinone = require('./spts/lib/allInOne');
  port = process.env.APP_PORT || 8000;
  app = connect();
  aio = allinone();
  app.use(connect["static"]("" + __dirname + "/public"));
  app.use('/s/', aio.middleWare);
  app.listen(port);
} catch (_error) {
  e = _error;
  console.log(e);
}
