// Generated by CoffeeScript 1.6.2
(function() {
  var AllInOne, exports;

  AllInOne = (function() {
    function AllInOne() {}

    AllInOne.prototype.middleWare = function(req, res, next) {
      var data;

      data = {
        responseData: {
          feed: {
            entries: [
              {
                title: 'mission',
                mission: 'mission'
              }, {
                title: 'mission',
                mission: 'mission'
              }, {
                title: 'mission',
                mission: 'mission'
              }, {
                title: 'mission',
                mission: 'mission'
              }, {
                title: 'mission',
                mission: 'mission'
              }
            ]
          }
        }
      };
      return res.end(JSON.stringify(data));
    };

    return AllInOne;

  })();

  exports = module.exports = function() {
    return new AllInOne;
  };

}).call(this);
